name: Release

on: push

jobs:

  Build-And-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Package release
        uses: papeloto/action-zip@v1
        with:
          files: dist/
          dest: release.zip
      - name: Push release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release.zip
